repos:
-   repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
    - id: black
      language_version: python3.10
-   repo: local
    hooks:
    - id: generate-requirements
      name: generates-requirements
      entry: bash -c 'pipreqs .'
      language: system
      pass_filenames: false
