[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "arachnida"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["srcs/"]

[project.scripts]
spider = "crawler:crawl"
scorpion = "exif_parser:parse"

[pytest]
testpaths = "tests"
