[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "arachnida"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["srcs"]

[project.scripts]
spider = "spider:crawl"
scorpio = "scorpio:parse"

[pytest]
testpaths = "tests"
